language: cpp

compiler: clang

env:
 - BUILD_TYPE=Debug
 - BUILD_TYPE=Release

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -qq doxygen valgrind

install:
 - cmake -H./ -BBuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DHEADLESS=ON
 - cd Build
 - make
 - cd ..

script:
 - cd Build/Output
 - ./HectUnitTests
 - ./HectSystemTests
 - valgrind ./HectUnitTests
 - valgrind ./HectSystemTests
