language: cpp

compiler:
 - gcc

env:
 - BUILD_TYPE=Debug
 - BUILD_TYPE=Release

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-4.9 doxygen valgrind
 - export C=gcc-4.9
 - export CXX=g++-4.9

install:
 - cmake -H./ -BBuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DHEADLESS=ON
 - cd Build
 - make
 - cd ..

script:
 - cd Build/Output
 - valgrind -q --leak-check=full --error-exitcode=1 ./HectUnitTests
 - valgrind -q --leak-check=full --error-exitcode=1 ./HectSystemTests
