language: cpp

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-4.9 libasound2-dev freeglut3 freeglut3-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev
 - export CXX="g++-4.9"
 - export CC="gcc-4.9"

install:
  - python prebuild.py
  - cd Build
  - make
  - cd ..
