language: cpp

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-4.8 doxygen libasound2-dev freeglut3 freeglut3-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev libx11-dev libxi-dev
 - export CC=gcc-4.8
 - export CXX=g++-4.8

install:
 - python build.py

script:
 - cd Build/Output
 - ./HectUnitTests
 - ./HectSystemTests HectSystemTests.config

