language: cpp

env:
 - BUILD_TYPE=Debug
 - BUILD_TYPE=Release

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++-5 valgrind
 - sudo add-apt-repository -y ppa:libreoffice/libreoffice-4-2
 - sudo apt-get update -qq
 - sudo apt-get install -qq doxygen
 - export CC=gcc-5
 - export CXX=g++-5

install:
 - cmake -H./ -BBuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DHECT_HEADLESS=ON
 - cd Build
 - make
 - cd ..

script:
 - cd Build/Output
 - valgrind -q --leak-check=full --error-exitcode=1 ./HectUnitTests
 - valgrind -q --leak-check=full --error-exitcode=1 ./HectSystemTests
