import glob
import os
import sys
import re
import xml.etree.ElementTree as ET

class ReflectType:
    def __init__(self, header, kind, name, values, properties):
        self.header = header
        self.kind = kind
        self.name = name
        self.values = values
        self.properties = properties
        
setter_regex = re.compile(".*Setter for property \<emphasis\>([a-zA-Z0-9]+)\<\/emphasis\>.*", re.DOTALL)
getter_regex = re.compile(".*Getter for property \<emphasis\>([a-zA-Z0-9]+)\<\/emphasis\>.*", re.DOTALL)

if __name__ == "__main__":
    types = []
    
    for file_name in glob.glob(sys.argv[1]):
        with open(file_name, "r") as in_file:
            xml_string = in_file.read()
            root = ET.fromstring(xml_string)
            for compounddef in root.iter("compounddef"):
                name = compounddef.find("compoundname").text
                header = compounddef.find("location")
                if not header is None:
                    header = header.attrib["file"]
                if compounddef.attrib["kind"] == "class":
                    kind = "Kind::Class"
                elif compounddef.attrib["kind"] == "struct":
                    kind = "Kind::Structure"
                elif compounddef.attrib["kind"] == "namespace":
                    kind = "Kind::Enumeration"
                else:
                    break;
                    
                if kind == "Kind::Enumeration":
                    if name != "hect":
                        values = []
                        for sectiondef in compounddef.iter("sectiondef"):
                            for memberdef in compounddef.iter("memberdef"):
                                for enumvalue in memberdef.iter("enumvalue"):
                                    values.append((enumvalue.find("name").text, name + "::" + enumvalue.find("name").text))
                        name = name + "::Enum"
                        types.append(ReflectType(header, kind, name, values, None))
                else:
                    is_template = False
                    for templateparamlist in compounddef.iter("templateparamlist"):
                        is_template = True
                    if not is_template and compounddef.attrib["prot"] == "public":
                        properties = { }
                        if kind == "Kind::Class":
                            for memberdef in root.iter("memberdef"):
                                if memberdef.attrib["kind"] == "function":
                                    detaileddescription = memberdef.find("detaileddescription")
                                    if not detaileddescription is None:
                                        text = str(ET.tostring(detaileddescription, encoding='utf8', method='xml'))
                                        if not text is None:
                                            setter_match = setter_regex.match(text)
                                            getter_match = getter_regex.match(text)
                                            if setter_match:
                                                property_name = setter_match.group(1)
                                                print("set" + property_name)
                                                if not property_name in properties:
                                                    properties[property_name] = { }
                                                properties[property_name]["setter"] = memberdef.find("name").text
                                            elif getter_match:
                                                property_name = getter_match.group(1)
                                                print("get" + property_name)
                                                if not property_name in properties:
                                                    properties[property_name] = { }
                                                properties[property_name]["getter"] = memberdef.find("name").text
                                                if not memberdef.find("type").text is None:
                                                    type_text = memberdef.find("type").text
                                                else:
                                                    type_text = memberdef.find("type").find("ref").text
                                                properties[property_name]["type"] = type_text.replace("const ", "").replace("&", "").strip()
                        types.append(ReflectType(header, kind, name, None, properties))

    with open(sys.argv[2], "w") as out_file:
        out_file.write("// This file is automatically generated\n\n")
        out_file.write("#include \"Hect/Reflection/Type.h\"\n")
        for type in types:
            out_file.write("#include \"" + type.header + "\"\n")
        out_file.write("\n")
        out_file.write("using namespace hect;\n")
        out_file.write("\n")
        out_file.write("class " + sys.argv[3] + "\n")
        out_file.write("{\n")
        out_file.write("public:\n")
        out_file.write("    " + sys.argv[3] + "()\n")
        out_file.write("    {\n")
        for type in types:
            out_file.write("        // " + type.name + "\n")
            out_file.write("        Type::addRegisterFunction([]()\n")
            out_file.write("        {\n")
            out_file.write("            Type& type = Type::create<" + type.name + ">(" + type.kind  + ", \"" + type.name + "\");\n")
            out_file.write("            type;\n")
            if not type.values is None:
                for value in type.values:
                    out_file.write("            Enum::add<" + type.name + ">(\"" + value[0] + "\", " + value[1] + ");\n")
            elif not type.properties is None:
                for property_name in type.properties:
                    property = type.properties[property_name]
                    out_file.write("            type.addProperty<" + type.name + ", " + property["type"] + ">(\"" + property_name + "\", &" + type.name + "::" + property["getter"] + ", &" + type.name + "::" + property["setter"] + ");\n")
            out_file.write("        });\n")
        out_file.write("    }\n")
        out_file.write("} _" + sys.argv[3] + ";\n")