---
modules:
  - type: Vertex
    path: Screen.glsl
  - type: Fragment
    path: Environment.glsl
uniforms:
  - name: view
    binding: ViewMatrix
  - name: diffuse_buffer
    binding: DiffuseBuffer
  - name: material_buffer
    binding: MaterialBuffer
  - name: position_buffer
    binding: PositionBuffer
  - name: normal_buffer
    binding: NormalBuffer
  - name: light_probe_texture
    binding: LightProbeTexture
depth_tested: false
blend_mode:
    source_factor: One
    destination_factor: One
